modules/pyramid/models/Node.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\models;

use app\helpers\Account;
use app\models\User;
use Exception;
use Yii;
use yii\db\ActiveRecord;
use yii\db\Transaction;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * This is the model class for table "node".
 *
 * @property integer $id
 * @property string $user_name
 * @property integer $type_id
 * @property integer $count
 * @property integer $time
 *
 * @property Type $type
 * @property User $user
 * @property Node[] $children
 */
class Node extends ActiveRecord
{
    public static function tableName() {
        return 'node';
    }

    public function rules() {
        return [
            [['user_name', 'type_id', 'count', 'time'], 'required'],
            [['type_id', 'count', 'time'], 'integer', 'min' => 0],
            [['user_name'], 'string', 'max' => 24],
            ['time', 'default', 'value' => $_SERVER['REQUEST_TIME']]
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_name' => Yii::t('app', 'Username'),
            'type_id' => Yii::t('app', 'Plan'),
            'count' => Yii::t('app', 'Counter'),
            'time' => Yii::t('app', 'Time'),
        ];
    }

    /**
     * @return User
     */
    public function getUser() {
        return $this->hasOne(User::class, ['name' => 'user_name']);
    }

    public function setUser(User $value) {
        $this->user_name = $value->name;
    }

    /**
     * @return Type
     */
    public function getType() {
        return Type::get($this->type_id);
    }

    public function setType(Type $value) {
        $this->type_id = $value->id;
    }

    public function countQueue() {
        return static::find()
            ->andWhere('time <= :time', [':time' => $this->time])
            ->andWhere(['type_id' => $this->type_id])
            ->sum('count');
    }

    public function decrement() {
        $this->count--;
        return $this->update(false, ['count']);
    }

    public static function rise() {
        /**
         * @var $nodes Node[]
         */
        $nodes = static::find()
            ->where('count <= 0')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC])
            ->all();

        $i = count($nodes);
        foreach($nodes as $node) {
            if ($node->type->isTornado()) {
                if ($tornado = Node::getTornadoExpectant()) {
                    $node = $tornado;
                }
            }
            $node->up();
        }

        return $i;
    }

    public function up() {
        $type = $this->getType();

        if ($type->income) {
            Income::makeFromNode($this);
        }

        if ($type->next_id) {
            $this->type_id = $type->next_id;
            if (!$this->invest()) {
                throw new Exception($this->dump());
            }
        }
        else {
            $this->reinvest();
            $this->delete();
        }
    }

    public function invest() {
        $this->count = $this->getType()->degree;
        if (!$this->time) {
            $this->time = $_SERVER['REQUEST_TIME'];
        }
        $expectant = static::getExpectant($this->type_id);
        if ($expectant && $expectant->type->isTornado()) {
            $expectant = static::getTornadoExpectant();
        }
        if ($expectant) {
            $expectant->decrement();
            if (Type::LEVEL2 == $expectant->type_id && 1 == $expectant->count) {
                Income::makeFromNode($expectant);
            }
        }
        if ($this->save()) {
            Account::add('profit', $this->getType()->getProfit());
            return true;
        }
        else {
            throw new Exception($this->dump());
        }
    }

    public function reinvest() {
        if ($this->getType()->reinvest) {
            $reinvest = new Node([
                'user_name' => $this->user_name,
                'type_id' => $this->getType()->reinvest
            ]);
            return $reinvest->invest();
        }
        return false;
    }

    /**
     * @param $type_id
     * @return Node
     */
    public static function getExpectant($type_id) {
        return static::find()->where(['type_id' => $type_id])->andWhere('count > 0')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC])->limit(1)->one();
    }

    /**
     * @return Node
     */
    public static function getTornadoExpectant() {
        return static::find()->where('type_id = 5 OR type_id = 6')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC])->limit(1)->one();
    }

    public function dump() {
        $bundle = [
            'id' => $this->id,
            'type_id' => $this->type_id,
            'count' => $this->count,
            'time' => date($this->time),
            'user_name' => $this->user_name,
            'account' => $this->user->account
        ];
        if (count($this->errors) > 0) {
            $bundle['errors'] = $this->errors;
        }
        if (count($this->user->errors) > 0) {
            $bundle['user_errors'] = $this->user->errors;
        }
        return json_encode($bundle, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    public function __toString() {
        return $this->id . ' ' . Type::get($this->type_id);
    }

    public function open(Transaction $transaction) {
        try {
            $sum = (int) Node::find()->where(['user_name' => $this->user_name])->count();
            $sum += (int) Income::find()->where(['user_name' => $this->user_name])->count();
            if ($this->invest()) {
                do {
                    $i = $this->rise();
                }
                while($i > 0);

                if (0 == $sum && $this->user->canChargeBonus()) {
                    $referral = $this->user->referral;
                    $referral->account += $this->type->bonus;
                    $referral->update(true, ['account']);
                    if (4 == $this->type->id) {
                        $count = $referral->getSponsors()
                            ->select('user_name')
                            ->joinWith('nodes')
                            ->groupBy('user_name')->count();
                        if ($count > 0 && 0 == $count % 10) {
                            $gift = new Gift(['user_name' => $referral->name]);
                            $gift->save();
                            Yii::$app->session->setFlash('success', Yii::t('app', 'Your referral may receive a gift'));
                        }
                    }
                }
                $transaction->commit();
                Yii::$app->session->setFlash('success', Yii::t('app', 'The plan is open'));
                return true;
            }
            else {
                Yii::$app->session->setFlash('error', $this->dump());
            }
        }
        catch(\Exception $ex) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('error', $ex->getMessage());
        }
        return false;
    }
}

modules/pyramid/controllers/NodeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\behaviors\Access;
use app\modules\pyramid\models\Gift;
use app\modules\pyramid\models\Node;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class NodeController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'compute' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index'],
                'manager' => ['create', 'update', 'delete', 'up']
            ],

            'cache' => [
                'class' => 'yii\filters\HttpCache',
                'cacheControlHeader' => 'must-revalidate, private',
                'only' => ['index'],
                'enabled' => false,
                'lastModified' => function ($action, $params) {
                    $query = Node::find();
                    if (isset($params['user'])) {
                        $query->where(['user_name' => $params['user']]);
                    }
                    return (int) $query->max('time');
                },
            ],
        ];
    }

    public function actionIndex($user = null, $id = null) {
        $parent = $id ? $this->findModel($id) : null;
        if (!Yii::$app->user->identity->isManager() && (!$parent && !$user)) {
            //(!$user && $parent && $parent->user_name != Yii::$app->user->identity->name)) {
            return $this->redirect(['index', 'user' => Yii::$app->user->identity->name]);
        }
        $query = Node::find()
            ->orderBy(['time' => SORT_DESC, 'id' => SORT_DESC]);
        if ($user) {
            $query->andWhere(['user_name' => $user]);
        }
        elseif ($parent) {
            $query
                ->andWhere('"time" < :time', [':time' => $parent->time])
                ->andWhere(['type_id' => $parent->type_id]);
        }
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => $query
            ]),
            'parent' => $parent
        ]);
    }

    public function actionCreate($id = null) {
        $model = new Node();
        if ($id) {
            $base = $this->findModel($id);
            $model->time = $base->time - 1;
            $model->type_id = $base->type_id;
        }
        elseif (isset($_GET['type_id'])) {
            $model->type_id = (int) $_GET['type_id'];
        }
        else {
            $model->time = time();
        }

        $is_post = $model->load(Yii::$app->request->post());
        if ($is_post) {
            $model->count = $model->getType()->degree;
            if ($is_post && $model->validate()) {
                if ($model->save(false)) {
                    return $this->redirect(['index', 'id' => $model->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', json_encode($model->errors, JSON_UNESCAPED_UNICODE));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionCompute($id) {
        $transaction = Yii::$app->db->beginTransaction();
        $model = $this->findModel($id);
        $model->open($transaction);
        return $this->redirect(['index']);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionGift() {
        return $this->render('gift', [
            'dataProvider' => new ActiveDataProvider([
                'query' => Gift::find(),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_DESC]
                ]
            ])
        ]);
    }

    public function actionGive($id) {
        $node = Gift::findOne($id)->give();
        if ($node) {
            return $this->redirect(['index', 'id' => $node->id]);
        }
        else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
            return $this->redirect(['gift']);
        }
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Node the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Node::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/controllers/TypeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\behaviors\Access;
use app\modules\pyramid\models\Gift;
use app\modules\pyramid\models\Income;
use app\modules\pyramid\models\Node;
use Yii;
use yii\base\InvalidParamException;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\modules\pyramid\models\Type;
use yii\web\NotFoundHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class TypeController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'open' => ['post'],
                ]
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['view']
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index', [
            'dataProvider' => new ArrayDataProvider([
                'allModels' => Type::all()
            ]),
        ]);
    }

    public function actionView($id) {
        $model = $this->findModel($id);
        if (Yii::$app->user->identity->account < $model->stake && !Yii::$app->session->getFlash('success')) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Insufficient funds'));
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionOpen($id) {
        if (!in_array($id, [1, 2, 3, 4])) {
            throw new InvalidParamException('id');
        }

        /** @var \app\models\User $me */
        $me = Yii::$app->user->identity;
        $type = $this->findModel($id);
        $node = new Node([
            'type' => $type,
            'user' => $me
        ]);

        if ($me->account >= $type->stake) {
            $me->account -= $type->stake;
            $transaction = Yii::$app->db->beginTransaction();
            if ($me->update(true, ['account'])) {
                $node->open($transaction);
            }
            else {
                Yii::$app->session->setFlash('error', json_encode($me, JSON_UNESCAPED_UNICODE));
            }
        }
        else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Insufficient funds'));
            return $this->redirect(['view', 'id' => $node->id]);
        }

        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Type the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if ($model = Type::get($id)) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/views/node/_form.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Type;
use app\widgets\AjaxComplete;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\pyramid\models\Node */
/* @var $form yii\widgets\ActiveForm */

$types = Type::getItems();
?>

<div class="type-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_name')->widget(AjaxComplete::class, [
        'route' => ['/user/complete']
    ]) ?>
    <?= $form->field($model, 'type_id')->dropDownList($types) ?>
    <?php
    if (!$model->isNewRecord) {
        echo $form->field($model, 'count');
    }
    ?>
    <?php
    array_unshift($types, Yii::t('app', 'Investment'), 0);
    unset($types[1]);
    echo Html::activeHiddenInput($model, 'time');
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord
            ? Yii::t('app', 'Create')
            : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/pyramid/views/node/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\pyramid\models\Type */

$this->title = Yii::t('app', 'Create Investment');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="node-create middle">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/gift.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Gift;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View
 * @var $dataProvider yii\data\ActiveDataProvider
 */

$this->title = Yii::t('app', 'Gifts');
?>
<div class="gift-index middle">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{pager}\n{errors}\n{summary}\n{items}",
        'columns' => [
            'id',
            [
                'attribute' => 'user_name',
                'format' => 'html',
                'value' => function(Gift $model) {
                    return Html::a($model->user_name, ['user/view', 'name' => $model->user_name]);
                }
            ],
            'time:datetime',
            [
                'attribute' => 'node_id',
                'label' => Yii::t('app', 'Action'),
                'format' => 'html',
                'value' => function(Gift $model) {
                    if ($model->node_id) {
                        return Html::a(Yii::t('app', 'View'),
                            ['index', 'id' => $model->node_id],
                            ['class' => 'btn btn-primary btn-xs']);
                    }
                    else {
                        return Html::a(Yii::t('app', 'Give'),
                            ['give', 'id' => $model->id],
                            ['class' => 'btn btn-success btn-sm']);
                    }
                }
            ],
        ],
    ]); ?>

</div>

modules/pyramid/views/node/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Node;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View
 * @var $parent Node
 * @var $dataProvider yii\data\ActiveDataProvider
 */

$user = isset($_GET['user']) ? $_GET['user'] : null;
$mine = !Yii::$app->user->isGuest && (Yii::$app->user->identity->isManager() || Yii::$app->user->identity->name == $user);
$manager = !Yii::$app->user->isGuest && Yii::$app->user->identity->isManager();
$title = $this->title = Yii::t('app', 'Investments');
$columns = [
    'id',
    [
        'attribute' => 'user_name',
        'format' => 'html',
        'value' => function(Node $model) {
            return Html::a($model->user_name, ['/user/view', 'name' => $model->user_name]);
        }
    ],
    'time:datetime',
    [
        'label' => Yii::t('app', 'Action'),
        'format' => 'html',
        'value' => function(Node $model) {
            return Html::a(Yii::t('app', 'View'), ['index', 'id' => $model->id],
                ['class' => 'btn btn-primary btn-xs']);
        }
    ]
];


if (isset($parent)) {
    $title = $parent->getType()->name . " #$parent->id ";
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investments'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $title;
    $this->title = $title;
    $title .= $mine ? Html::a($parent->user_name, ['/user/view', 'name' => $parent->user_name]) : $parent->user_name;

}
else {
    $additional = [$columns[0],
        [
            'attribute' => 'type_id',
            'label' => Yii::t('app', 'Plan'),
            'format' => 'html',
            'value' => function(Node $model) {
                return Html::a($model->getType()->name, ['type/view', 'id' => $model->type_id]);
            }
        ]
    ];
    if ($user) {
        $this->title = Yii::t('app', 'Investments of user') . ' ' . $user;
        if ($mine) {
            $title = Yii::t('app', 'Investments of user') . ' ' . Html::a($user, ['user/view', 'name' => $user]);
        }
        else {
            $title = $this->title;
        }
    }
    $columns = array_merge($additional, array_slice($columns, 1));
}

?>
<div class="invest middle">
    <div>
        <h1><?= $title ?></h1>

        <div class="form-group">
            <?php
            if (empty($parent)) {
                if ($manager) {
                    echo Html::a(Yii::t('app', 'Create'), ['create'], ['class' => 'btn btn-primary']);
                }
                else {
                    echo Html::a(Yii::t('app', 'Open'), ['/pyramid/type/index'], ['class' => 'btn btn-success']);
                }
            }
            elseif ($manager) {
                    echo implode(' ', [
                        Html::a(Yii::t('app', 'Update'), ['update', 'id' => $parent->id], ['class' => 'btn btn-primary']),
                        Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $parent->id], ['class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                                'method' => 'post',
                            ]]),
                        Html::a(Yii::t('app', 'Compute'), ['compute', 'id' => $parent->id], ['class' => 'btn btn-warning',
                            'data' => ['method' => 'post']])
                    ]);
                }
            ?>
        </div>

        <?php
        if (isset($parent)) {
            echo Html::tag('p', Yii::t('app', 'Remains to exit') . ': ' . $parent->countQueue());
        }
        ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'emptyText' => '',
        'showOnEmpty' => false,
        'columns' => $columns,
    ])
    ?>

</div>

modules/pyramid/views/node/update.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\pyramid\models\Type */

$this->title = Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['invest', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="type-update middle">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/view.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Node */

$this->title = $model->type->name . " #$model->id";
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investment'), 'url' => ['invest']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-view middle">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <div id="matrix">
        <h2><?= count($model->children) ?> из <?= $model->type->degree ?></h2>
        <?php
        foreach($model->children as $child) {
            echo Html::a($child->user_name, ['user/view', 'name' => $child->user_name]);
        }
        ?>
    </div>
</div>