controllers/HomeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;


use app\models\Record;
use app\modules\article\models\Article;
use app\modules\invoice\models\Invoice;
use app\models\User;
use app\helpers\SQL;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class HomeController extends Controller {
    public function actionIndex() {
        return $this->render('index', [
            'statistics' => $this->renderPartial('statistics', ['statistics' => static::statistics()]),
            'news' => Article::find()->where('"name" is null')->orderBy(['id' => SORT_DESC])->limit(3)->all()
        ]);
    }

    public function actionError() {
        $exception = Yii::$app->getErrorHandler()->exception;
        $message = $exception->getMessage();
        if ($exception instanceof ForbiddenHttpException) {
            $message = $message ? Yii::t('app', $message) : Yii::t('app', 'Forbidden');
        }
        if ($message) {
            Yii::$app->session->setFlash('error', $message);
        }
        return $this->render('error', [
            'exception' => $exception
        ]);
    }

    public static function statistics() {
        $started = strtotime(SQL::queryCell('SELECT "time" FROM "journal" WHERE id = 1'));
        $invested = (int) SQL::queryCell('SELECT count(*) FROM "node"');
        return [
            'Started' => date('d-m-Y', $started),
            'Running days' => floor((time() - $started)/(3600 * 24)),
            'Users' => User::find()->count(),
            'Total deposited' => Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount > 0')->sum('amount'),
            'Total withdraw' => - Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount < 0')->sum('amount'),
            'Number of investments' => $invested
        ];
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\Login;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use app\modules\pyramid\models\Node;
use app\modules\pyramid\models\Type;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['view', 'update', 'index'],
                'manager' => ['complete', 'account'],
                'admin' => ['create', 'delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($name = null) {
        /* @var User $me */
        $me = Yii::$app->user->identity;
        $model = $name ? $this->findModel($name) : $me;
        if (!$name || $me->isManager() || $model->ref_name == $name || User::find()->where([
                'ref_name' => $me->name, 'name' => $name])->count() > 0) {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
        throw new ForbiddenHttpException();
    }

    public function actionCreate() {
        $model = new User([
            'account' => 0
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'bundle' => []
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
                if ($model->isAttributeChanged('perfect', false)) {
                    $model->perfect = $model->getOldAttribute('perfect');
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Wallet can change admin only'));
                }
            }

            if ('Europe/Moscow' == $model->timezone) {
                $model->timezone = null;
            }

            foreach(['skype', 'country', 'phone', 'forename', 'surname'] as $name) {
                if (empty($model->$name)) {
                    $model->$name = null;
                }
            }

            if (Yii::$app->user->identity->name == $model->name && $model->isAttributeChanged('timezone', false)) {
                $_SESSION['timezone'] = $model->timezone;
            }

            if ($model->save()) {
                if (Yii::$app->user->identity->isAdmin()) {
                    return $this->redirect(['view', 'name' => $model->name]);
                }
                else {
                    return $this->redirect(['view']);
                }
            }
        }

        if (!$model->timezone) {
            $model->timezone = 'Europe/Moscow';
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup() {
        $model = new User([
            'scenario' => 'signup'
        ]);

        $bundle = [];
        if (!empty($_GET)) {
            $attributes = $model->activeAttributes();
            foreach ($_GET as $key => $value) {
                if (in_array($key, $attributes)) {
                    $model->$key = $value;
                } else {
                    $bundle[$key] = $value;
                }
            }
        }

        if ($model->load(Yii::$app->request->post())) {
            $bundle_post = Yii::$app->request->post('bundle');
            if ($bundle_post) {
                $bundle = array_merge($bundle_post, $bundle);
            }

            if (preg_match('|U\w{7}|', $model->name)) {
                $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
            } elseif ($model->validate()) {
                $model->generateCode();
                $model->status = User::PLAIN;
                $model->setBundleFromAttributes(['hash'], true, $bundle);
                $model->save(false);
                $url = Url::to(['email', 'code' => $model->code], true);
                if ($model->sendEmail([
                    'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Signup'),
                    'content' => Yii::t('app', 'To confirm your registration click on the <a href="{url}">link</a>', [
                        'url' => $url,
                    ])
                ])
                ) {
                    Yii::$app->session->setFlash('info', Yii::t('app', 'Check your email'));
                } else {
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Email send error'));
                }
                return $this->redirect(['home/index']);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'bundle' => $bundle
        ]);
    }

    public function actionLogin() {
        $model = new Login();

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                                $user->save();
                            }
                            if (Yii::$app->user->login($user, $model->remember ? $user->duration * 60 : 0)) {
                                $bundle = $user->getBundle();
                                if ($bundle && isset($bundle['node_id'])) {
                                    $node_id = (int) $bundle['node_id'];
                                    $user->setBundle(null);
                                    $user->save();
                                    if (Node::find()->where(['id' => $node_id])->count() > 0) {
                                        Yii::$app->session->addFlash('success', Yii::t('app', 'Congratulation! You receive a gift'));
                                        return $this->redirect(['/pyramid/node/index', 'id' => $node_id]);
                                    }
                                }
                                return $this->redirect(['view']);
//                                return $this->actionView($user->name);
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'

views/home/error.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $exception \app\JournalException */

$this->title = $exception->event;
?>
<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

views/home/index.php
<?php
/**
 * @link http://zenothing.com/
 * @var string $statistics
 * @var yii\web\View $this
 * @var Article[] $news
 */

use app\modules\article\models\Article;
use app\modules\feedback\controllers\FeedbackController;
use app\modules\pyramid\models\Type;
use yii\helpers\Html;
use yii\web\JqueryAsset;

$this->registerJsFile('/js/lightslider.js', ['depends' => [JqueryAsset::class]]);
$this->registerCssFile('/css/lightslider.css');

$benefits = [
    'Доступный вход',
    'Никаких приглашений',
    'Моментальные выплаты'
];

$this->registerMetaTag([
    'name' => 'description',
    'content' => implode(' ⬤ ', $benefits)
]);
?>
<article class="home-index">
    <section class="cloud center">
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </section>
    <section class="video center">
        <div class="row">
            <div class="exchangers">
                <h3>Обменники</h3>
                <img src="/images/dollar.gif" />
                <a href="https://magneticexchange.com/?p=5301" title="Magnetic Exchange - сервис обмена Perfect
                    Money, Neteller, Payza, Solid Trust Pay, Яндекс Денег, Payweb, RedPass и Paxum">
                    <img src="http://ad.magneticexchange.com/ru_125_125.gif" alt="Magnetic Exchange - сервис обмена
                        Perfect Money, Neteller, Payza, Solid Trust Pay, Яндекс Денег, Payweb, RedPass и Paxum" /></a>
                <a href="https://xchange.cc/?R=13966463495285">
                    <img src="https://xchange.cc/banner/black/125x125.gif"></a>
            </div>
            <div class="ipad">
                <iframe frameborder="0" src="//www.youtube.com/embed/s2tGLEd5x6M"></iframe>
            </div>
            <?= $this->renderFile('@app/modules/article/views/article/view.php', [
                'model' => Article::findOne(['name' => 'important'])
            ]) ?>
        </div>
    </section>
    <section class="pussy">
        <div>
            <p>
                <a href="http://perfectmoney.is" title="Perfect Money - новое поколение платежных систем Интернета">
                    <img hspace="5" src="/images/perfectmoney.jpg" />
                </a>
            </p>
            <p>Программа работает по принципу одной быстро движущейся общей очереди, 1x3 под одного встают
                три приглашенных и верхний в очереди получает выплату. Приглашения по реферальной ссылке,
                реферальная программа.</p>
            <p>Участник, после регистрации выбирает вариант входа один из четырех, может заходить на все четыре.</p>

            <p>Вход на 10 дол, после оплаты через перфект мани, партнер встает в очередь на получение 30 дол.
                После того, как под него в одну очередь зашло три человека он получает 30 дол., из них 10 дол.
                реинвест в конец очереди, 17 дол. на вывод Вашего кошелька Perfect Money.</p>

            <p>Вход на 30 дол., после оплаты через перфект мани, партнер встает в очередь на получение 90 дол.
                После того, как под него зашло три человека в одну общею очередь, он получает 90 дол.,
                из них 30 дол. реинвест в конец очереди, 50 дол. на вывод Вашего кошелька Perfect Money.</p>

            <p>Вход на 60 дол., после оплаты через перфект мани, партнер встает в очередь на получение 180 дол.
                После того, как под него в одну очередь зашло три человека он получает 180 дол., из них 60 дол.,
                реинвест в конец очереди, 100 на вывод Вашего кошелька Perfect Money.</p>

            <p>4 - программа 1x3 Вход на 100 дол., после оплаты через перфект мани, партнер встает в очередь
                на получение 300 дол. После того, как под него в общею очередь зашло три человека он получает 300 дол.,
                (на руки вывода нет) для перехода во вторую программу.</p>
            <p>2 - программа 1x3 переход 300 дол., после того как под него в одну очередь, встанет один человек,
                он получает 250 дол. на вывод, 50 админу. Встал в тройку следующий, получает 250 дол. Встал третий
                человек получает на вывод 200 дол., и 100 дол уходят реинвестом вниз очереди программы на сто.</p>
        </div>
    </section>
    <section class="news center">
        <div class="block-table">
            <?php
            echo Html::tag('h2', Yii::t('app', 'News'));

            $titles = [];
            $contents = [];
            $links = [];
            foreach($news as $article) {
                $titles[] = Html::tag('div', Html::tag('h3', $article->title));
                $contents[] = Html::tag('div', substr($article, 0, 200));
                $links[] = Html::tag('div',
                    Html::a(Yii::t('app', 'Read more'),
                        ['/article/article/view', 'id' => $article->id],
                        ['class' => 'button']));
            }

            echo Html::tag('div', implode('', $titles));
            echo Html::tag('div', implode('', $contents));
            echo Html::tag('div', implode('', $links));
            ?>
        </div>
    </section>
    <section class="rubbish center">
        <div>
            <h2><strong>Что</strong> говорят Люди?</h2>
            <div class="row">
                <div>
                    <img src="/images/man.png">
                </div>
                <div>
                    <div>В компании "Денежный Торнадо" может стать любой желающий достигший совершеннолетия. Оплатив вход единоразово в одну или несколько программ, Вы становитесь полноценным участником. Доступно для ВСЕХ участников интернет - ресурса.</div>
                </div>
                <div>
                    <img src="/images/woman.png">
                </div>
                <div>
                    <div>Простой понятный и доступный маркетинг, без квалификаций, без подтверждений, нет ежемесячной абонентской платы, партнерская программа, одним словом есть ВСЕ необходимое.</div>
                </div>
            </div>
        </div>
    </section>
    <section class="plans center">
        <div>
            <h2><strong>Планы</strong> и ценообразования</h2>
            <?php
            $names = [];
            $signups = [];
            foreach(Type::all() as $type) {
                if ($type->visibility) {
                    $names[] = Html::tag('div',
                        Html::tag('div', Html::tag('div', $type->name) . Html::tag('div', '$' . $type->stake), [
                            'class' => 'inner'
                        ]));

                    $signups[] = Html::tag('div',
                        Html::tag('div', Html::a(Yii::t('app', 'Signup'), ['/user/signup', 'type_id' => $type->id], ['class' => 'button']), [
                            'class' => 'inner'
                        ]));
                }
            }
            ?>
            <div class="block-table">
                <div>
                    <?= implode("\n", $names) ?>
                </div>
                <div>
                    <?= implode("\n", $signups) ?>
                </div>
            </div>
        </div>
    </section>
    <section class="feedback center">
        <?= $this->renderFile('@app/modules/feedback/views/feedback/create.php', [
            'model' => FeedbackController::create()
        ]) ?>
    </section>
</article>
<?php
$this->title = Yii::$app->name;
?>

views/home/page.php
<?php
/**
 * @link http://zenothing.com/
*/
use yii\bootstrap\Html;

$title = $model->getTitle();
if ($title) {
    $this->title = $title;
}
?>
<div class="page">
    <?php
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
        echo Html::a(Yii::t('app', 'Update'), ['update', 'name' => $model->name], ['class' => 'btn btn-primary']);
    }
    ?>

    <article><?= $model->content ?></article>
</div>

views/home/statistics.php
<?php
/**
 * @link http://zenothing.com/
*/
use yii\helpers\Html;
?>
<div class="statistics">
<?php
foreach($statistics as $name => $value) {
    echo Html::tag('div', Html::tag('span', Yii::t('app', $name) . ':') . Html::tag('span', $value));
}
?>
</div>

views/home/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use dosamigos\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= Html::activeHiddenInput($model, 'name') ?>
    <?= $form->field($model, 'content')->widget(CKEditor::class, [
        'preset' => 'full'
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Update'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>