modules/invoice/models/Invoice.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\invoice\models;

use app\behaviors\Journal;
use app\helpers\JournalException;
use app\models\User;
use Yii;
use yii\db\ActiveRecord;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * This is the model class for table "invoice".
 *
 * @property integer $id
 * @property string $user_name
 * @property number $amount
 * @property integer $batch
 * @property string $status
 *
 * @property User $user
 */
class Invoice extends ActiveRecord
{
    public static $statuses = [
        'create' => 'Created',
        'invalid_amount' => 'Invalid amount',
        'invalid_receiver' => 'Invalid receiver',
        'invalid_batch' => 'Transaction ID does not match',
        'invalid_response' => 'Unknown server response',
        'invalid_hash' => 'Invalid hash',
        'invalid_currency' => 'Invalid currency',
        'insufficient_funds' => 'Insufficient funds in the account user',
        'no_qualification' => 'User does not qualify',
        'cancel' => 'Cancel',
        'fail' => 'Error',
        'success' => 'Completed'
    ];

    public static function tableName() {
        return 'invoice';
    }

    public function traceable() {
        return ['status'];
    }

    public function behaviors() {
        return [
            Journal::class
        ];
    }

    public function rules() {
        return [
            [['user_name', 'amount'], 'required'],
            [['amount'], 'number'],
            [['user_name', 'status'], 'string', 'max' => 16]
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public static function find() {
        return parent::find()->andWhere('"status" <> \'delete\'');
    }

    public function scenarios() {
        return [
            'default' => ['user_name', 'amount', 'status'],
            'payment' => ['user_name', 'amount'],
            'withdraw' => ['user_name', 'amount'],
            'manage' => ['user_name', 'amount', 'status'],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_name' => Yii::t('app', 'Username'),
            'amount' => Yii::t('app', 'Amount'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    public function getUser() {
        return $this->hasOne(User::class, ['name' => 'user_name']);
    }

    public function saveStatus($status) {
        $this->status = $status;
        return $this->save();
    }

    public function __toString() {
        return Yii::t('app', $this->amount < 0 ? 'Withdraw #{id} for ${amount}' : 'Payment #{id} for ${amount}', [
            'id' => $this->id,
            'amount' => abs($this->amount)
        ]);
    }

    public function throwJournalException($message) {
        throw new JournalException(static::tableName(), $this->id, 'fail', $message);
    }

    public function journalView() {
        return __DIR__ . '/../views/invoice/journal.php';
    }

    public function url() {
        return ['/invoice/invoice/view', 'id' => $this->id];
    }
}

modules/invoice/controllers/InvoiceController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\invoice\controllers;

use app\behaviors\Access;
use app\behaviors\NoTokenValidation;
use app\modules\invoice\models\Withdrawal;
use app\modules\invoice\models\Invoice;
use app\modules\invoice\models\search\Invoice as InvoiceSearch;
use Exception;
use Yii;
use yii\db\Transaction;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class InvoiceController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'success' => ['post'],
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['success', 'fail', 'index', 'view', 'create'],
                'manager' => ['withdraw', 'update', 'delete']
            ],

            'no_csrf' => [
                'class' => NoTokenValidation::class,
                'only' => ['success', 'fail'],
            ]
        ];
    }

    public function actionIndex($user = null, $scenario = null) {
        $searchModel = new InvoiceSearch();
        if (!Yii::$app->user->identity->isManager()) {
            if (!$user) {
                $url = ['index', 'user' => Yii::$app->user->identity->name];
                if ($scenario) {
                    $url['scenario'] = $scenario;
                }
                return $this->redirect($url);
            }
            elseif (!Yii::$app->user->identity->isManager() && $user != Yii::$app->user->identity->name) {
                throw new ForbiddenHttpException('Forbidden');
            }
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate($scenario = 'payment', $amount = null) {
        if (!in_array($scenario, ['payment', 'withdraw'])) {
            throw new ForbiddenHttpException();
        }

        $model = new Invoice([
            'user_name' => Yii::$app->user->identity->name,
            'scenario' => $scenario
        ]);

        if ($amount) {
            $model->amount = $amount;
        }

        if ($model->load(Yii::$app->request->post())) {
            if ('withdraw' == $model->scenario) {
                $model->amount = - abs($model->amount);
                if (abs($model->amount) > $model->user->account) {
                    Yii::$app->session->setFlash('error', Yii::t('app', Invoice::$statuses['insufficient_funds']));
                    $model->amount = $model->user->account;
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $model->scenario = 'manage';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $invoice = $this->findModel($id);
        if ('success' == $invoice->status) {
            $invoice->saveStatus('delete');
        }
        else {
            $invoice->delete();
        }

        return $this->redirect(['index']);
    }

    public function actionSuccess($id) {
        $transaction = Yii::$app->db->beginTransaction();
        $invoice = $this->findModel($id);
        $string = $string= $_POST['PAYMENT_ID']
            .':'.$_POST['PAYEE_ACCOUNT']
            .':'.$_POST['PAYMENT_AMOUNT']
            .':'.$_POST['PAYMENT_UNITS']
            .':'.$_POST['PAYMENT_BATCH_NUM']
            .':'.$_POST['PAYER_ACCOUNT']
            .':'. Yii::$app->perfect->hashAlternateSecret()
            .':'.$_POST['TIMESTAMPGMT'];
        $user = $invoice->user;
        if (Yii::$app->user->identity->name != $invoice->user_name) {
            $transaction->rollBack();
            throw new ForbiddenHttpException(Yii::t('app', 'You can only change the status of your payments'));
        }
        elseif ('success' == $invoice->status) {
            $transaction->rollBack();
            Yii::$app->session->setFlash('success', Yii::t('app', 'Payment has already done previously'));
        }
        elseif (strtoupper(md5($string)) != $_POST['V2_HASH']) {
            $invoice->saveStatus('invalid_hash');
            Yii::$app->session->setFlash('error', Yii::t('app', Invoice::$statuses['invalid_hash']));
        }
        elseif ($invoice->amount != $_POST['PAYMENT_AMOUNT']) {
            $invoice->saveStatus('invalid_amount');
            Yii::$app->session->setFlash('error', Yii::t('app', Invoice::$statuses['invalid_amount']));
        }
        elseif (Yii::$app->perfect->wallet != $_POST['PAYEE_ACCOUNT']) {
            $invoice->saveStatus('invalid_receiver');
            Yii::$app->session->setFlash('error', Yii::t('app', 'Wrong recipient {wallet}', [
                'wallet' =>  $_POST['PAYEE_ACCOUNT'],
            ]));
        }
        elseif ('USD' != $_POST['PAYMENT_UNITS']) {
            $invoice->saveStatus('invalid_currency');
            Yii::$app->session->setFlash('error', Yii::t('app', Invoice::$statuses['invalid_currency']));
        }
        else {
            $user->account += $invoice->amount;
            if ($invoice->saveStatus('success') && $user->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', Yii::t('app', 'Payment #{id} completed', [
                    'id' => $invoice->id,
                ])));
                if (isset($_SESSION['type_id'])) {
                    $type_id = (int) $_SESSION['type_id'];
                    unset($_SESSION['type_id']);
                    $transaction->commit();
                    return $this->redirect(['/pyramid/type/view', 'id' => $type_id]);
                }
            }
            else {
                $invoice->saveStatus('fail');
                Yii::$app->session->setFlash('error', Yii::t('app', 'Cannot save payment'));
            }
        }
        $transaction->commit();

        return $this->render('view', [
            'model' => $invoice
        ]);
    }

    public function actionSss($id) {
        $transaction = Yii::$app->db->beginTransaction();
        $invoice = $this->findModel($id);
        $user = $invoice->user;
        $user->account += $invoice->amount;
        if ($invoice->saveStatus('success') && $user->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', Yii::t('app', 'Payment #{id} completed', [
                'id' => $invoice->id,
            ])));
            if (isset($_SESSION['type_id'])) {
                $type_id = (int) $_SESSION['type_id'];
                unset($_SESSION['type_id']);
                $transaction->commit();
                return $this->redirect(['/pyramid/type/view', 'id' => $type_id]);
            }
        }
        else {
            $invoice->saveStatus('fail');
            Yii::$app->session->setFlash('error', Yii::t('app', 'Cannot save payment'));
        }

        return $this->render('view', [
            'model' => $invoice
        ]);
    }

    public function actionFail($id) {
        $invoice = $this->findModel($id);

        if (Yii::$app->user->identity->name != $invoice->user_name) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can only change the status of your payments'));
        }
        else {
            $invoice->saveStatus('cancel');
            Yii::$app->session->setFlash('error', Yii::t('app', 'You cancel payment'));
        }

        return $this->render('view', [
            'model' => $invoice
        ]);
    }


    public function actionWithdraw($id) {
        $transaction = Yii::$app->db->beginTransaction();
        $invoice = $this->findModel($id);
        try {
            $invoice->scenario = 'withdraw';
            if ('success' == $invoice->status) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('info', Yii::t('app', 'Payment has already done previously'));
            }
            elseif (abs($invoice->amount) > $invoice->user->account) {
                $invoice->throwJournalException(Yii::t('app', Invoice::$statuses['insufficient_funds']));
            }
            else {
                if (!Yii::$app->perfect->id) {
                    static::withdrawSuccessful($invoice, $transaction);
                    return $this->render('view', [
                        'model' => $invoice
                    ]);
                }
                else {
                    $withdrawal = Withdrawal::fromInvoice($invoice);
                    $response = file_get_contents('https://perfectmoney.is/acct/confirm.asp?' . $withdrawal);
                    if (!preg_match('/<h1>(.*)<\/h1>/', $response, $result)) {
                        $invoice->throwJournalException($response);
                    } elseif ('Spend' != $result[1]) {
                        $invoice->throwJournalException($result[1]);
                    } elseif (!preg_match_all("/<input name='(.*)' type='hidden' value='(.*)'>/",
                        $response, $result, PREG_SET_ORDER)
                    ) {

modules/invoice/views/invoice/_form.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\modules\invoice\models\Invoice;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\invoice\models\Invoice */
/* @var $form yii\widgets\ActiveForm */
$statuses = [];
foreach(Invoice::$statuses as $key => $value) {
    $statuses[$key] = Yii::t('app', $value);
}
?>

<div class="invoice-form">

    <?php $form = ActiveForm::begin();

    if ('manage' == $model->scenario) {
        echo $form->field($model, 'user_name')->textInput(['maxlength' => true]);
        echo $form->field($model, 'status')->dropDownList($statuses);
    }
    echo$form->field($model, 'amount')->textInput(['maxlength' => true]);
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'),
            ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/invoice/views/invoice/_search.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\Invoice */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="invoice-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_name') ?>

    <?= $form->field($model, 'amount') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/invoice/views/invoice/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\invoice\models\Invoice */

$this->title = Yii::t('app', 'payment' == $model->scenario ? 'Payment' : 'Withdraw');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-create middle">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/invoice/views/invoice/index.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\modules\invoice\models\Invoice;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Invoice */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Invoices');

$actions = ['class' => 'yii\grid\ActionColumn'];
if (!Yii::$app->user->identity->isManager()) {
    $actions['template'] = '{view}';
}

$columns = ['id'];

if (empty($_GET['user'])) {
    $columns[] = 'user_name';
}

$columns[] = [
    'attribute' => 'amount',
    'value' => function(Invoice $model) {
        return isset($_GET['scenario']) ? abs($model->amount) : $model->amount;
    }
];
$columns[] = [
    'attribute' => 'status',
    'format' => 'html',
    'value' => function(Invoice $model) {
        $status = Yii::t('app', Invoice::$statuses[$model->status]);
        if ($model->amount < 0 && 'success' != $model->status && Yii::$app->user->identity->isManager()) {
            $status .= ' ' .Html::a(Yii::t('app', 'Withdraw'),
                ['withdraw', 'id' => $model->id], ['class' => 'btn btn-warning btn-xs']);
        }
        return $status;
    }
];
$columns[] = $actions;
?>
<div class="invoice-index middle">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="form-group">
        <?php if (!Yii::$app->user->identity->isManager()): ?>
        <?= Html::a(Yii::t('app', 'Pay'), ['create', 'scenario' => 'payment'], ['class' => 'btn btn-success']); ?>
        <?php
        if (Yii::$app->user->identity->account > 0) {
            echo Html::a(Yii::t('app', 'Withdraw'), ['create', 'scenario' => 'withdraw'], ['class' => 'btn btn-primary']);
        }
        ?>
        <?php endif ?>
    </div>

    <div class="form-group">
        <?= Yii::t('app', 'Show') ?>:
        <?= empty($_GET['scenario']) ? 'all' : Html::a(Yii::t('app', 'all'), ['index']) ?>
        <?= isset($_GET['scenario']) && 'payment' == $_GET['scenario'] ? Yii::t('app', 'payments')
            : Html::a(Yii::t('app', 'payments'), ['index', 'scenario' => 'payment']) ?>
        <?= isset($_GET['scenario']) && 'withdraw' == $_GET['scenario'] ? Yii::t('app', 'withdrawals')
            : Html::a(Yii::t('app', 'withdrawals'), ['index', 'scenario' => 'withdraw']) ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
    ]); ?>

</div>

modules/invoice/views/invoice/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\modules\invoice\models\Invoice;

$info = $record->info;
if ($info) {
    if (isset($info['status'])) {
        echo Yii::t('app', Invoice::$statuses[$info['status']]);
    }
}

modules/invoice/views/invoice/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\invoice\models\Invoice */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Invoice',
]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="invoice-update middle">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/invoice/views/invoice/view.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\modules\invoice\models\Invoice;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\invoice\models\Invoice */

$this->title = $model;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Invoices'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-view middle">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="form-group">
        <?php if (Yii::$app->user->identity->isManager()): ?>
            <?php
            if ('success' != $model->status && $model->amount < 0) {
                echo Html::a(Yii::t('app', 'Withdraw'), ['withdraw', 'id' => $model->id], ['class' => 'btn btn-warning']);
            }
            ?>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        <?php
        elseif ('success' != $model->status && $model->amount > 0):
            echo Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST');
            echo Html::hiddenInput('PAYEE_ACCOUNT', Yii::$app->perfect->wallet);
            echo Html::hiddenInput('PAYMENT_AMOUNT', $model->amount);
            echo Html::hiddenInput('PAYEE_NAME', Yii::$app->name);
            echo Html::hiddenInput('PAYMENT_UNITS', 'USD');
            echo Html::hiddenInput('PAYMENT_ID', $model->status);
            echo Html::hiddenInput('STATUS_URL', Url::to(['invoice/view', 'id' => $model->id], true));
            echo Html::hiddenInput('PAYMENT_URL', Url::to(['invoice/success', 'id' => $model->id], true));
            echo Html::hiddenInput('NOPAYMENT_URL', Url::to(['invoice/fail', 'id' => $model->id], true));
            echo Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME');
            echo Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name);
            echo Html::button(Yii::t('app', 'Pay'), [
                'name' => 'PAYMENT_METHOD',
                'type' => 'submit',
                'class' => 'btn btn-success'
            ]);
            echo Html::endForm();
        endif;
        ?>
    </div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'user_name',
                'format' => 'html',
                'value' => Html::a($model->user_name, ['/user/view', 'name' => $model->user_name])
            ],
            [
                'attribute' => 'amount',
                'value' => '$' . abs($model->amount)
            ],
            [
                'attribute' => 'status',
                'value' => Yii::t('app', Invoice::$statuses[$model->status])
            ]
        ],
    ]) ?>

</div>